name: Release

on:
  push:

jobs:
  build:
    name: Build and Release (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15-intel]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-cargo-release

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            JOBS=$(nproc)
          else
            JOBS=$(sysctl -n hw.ncpu)
          fi
          echo "Building with $JOBS jobs"
          CUDARC_CUDA_VERSION="12050" cargo build --release -j $JOBS

      - name: Prepare binary
        shell: bash
        run: |
          mkdir -p staging
          cp target/release/dpsn staging/dpsn
          if [ "${{ matrix.os }}" = "macos-15-intel" ]; then
            cd staging && tar czvf ../dpsn-apple-darwin.tar.gz dpsn
          else
            cd staging && tar czvf ../dpsn-x86_64-unknown-linux-gnu.tar.gz dpsn
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: DPSN
          files: |
            dpsn-apple-darwin.tar.gz
            dpsn-x86_64-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
